# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
